import AppKit
import CryptoKit
import Foundation

/// macOS has no "pasteboard changed" notification, so like every clipboard
/// manager we poll `changeCount` — a cheap integer compare a few times a second.
final class ClipboardMonitor {
    static let shared = ClipboardMonitor()

    /// Marker types that password managers and transient-copy tools set to ask
    /// clipboard managers not to record a copy. Honouring these is what keeps
    /// the history from becoming a plaintext password log.
    private static let concealedMarkers: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "de.petermaurer.TransientPasteboardType",
        "Pasteboard generator type",
    ]

    var onNewClip: (() -> Void)?

    private let pasteboard = NSPasteboard.general
    private var lastChangeCount: Int
    private var timer: Timer?
    private let settings = Settings.shared

    private init() {
        lastChangeCount = pasteboard.changeCount
    }

    func start() {
        timer?.invalidate()
        let interval = max(0.05, settings.pollInterval)
        let t = Timer(timeInterval: interval, repeats: true) { [weak self] _ in self?.tick() }
        t.tolerance = interval / 4
        RunLoop.main.add(t, forMode: .common)
        timer = t
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    func restart() { start() }

    /// Called after we write to the pasteboard ourselves, so pasting an old
    /// item doesn't get recorded as a brand-new copy.
    func suppressCurrentChange() {
        lastChangeCount = pasteboard.changeCount
    }

    private func tick() {
        let current = pasteboard.changeCount
        guard current != lastChangeCount else { return }
        lastChangeCount = current
        capture()
    }

    private func capture() {
        guard let items = pasteboard.pasteboardItems, let item = items.first else {
            debug("change \(pasteboard.changeCount): no pasteboard items")
            return
        }

        if debugEnabled {
            let all = items.enumerated().map { i, it in
                "[\(i)] " + it.types.map { t in
                    "\(t.rawValue)(\(it.data(forType: t)?.count ?? -1)b)"
                }.joined(separator: " ")
            }.joined(separator: " | ")
            debug("change \(pasteboard.changeCount) from \(NSWorkspace.shared.frontmostApplication?.bundleIdentifier ?? "nil"): \(all)")
        }

        if settings.ignoreConcealed {
            let present = Set(items.flatMap { $0.types.map(\.rawValue) })
            let hits = present.intersection(Self.concealedMarkers)
            if !hits.isEmpty {
                debug("SKIP concealed: \(hits.joined(separator: ","))")
                return
            }
        }

        let front = NSWorkspace.shared.frontmostApplication
        let bundleID = front?.bundleIdentifier
        if let bundleID, settings.excludedBundleIDs.contains(bundleID.lowercased()) {
            debug("SKIP excluded app \(bundleID)")
            return
        }
        // Never record our own panel's activity.
        if bundleID == Bundle.main.bundleIdentifier {
            debug("SKIP own app")
            return
        }
        let appName = front?.localizedName

        let kind: ClipKind
        var text = ""
        var blob: Data?

        if let urls = pasteboard.readObjects(forClasses: [NSURL.self]) as? [URL], !urls.isEmpty {
            kind = .fileURL
            text = urls.map(\.path).joined(separator: "\n")
        } else if settings.captureImages, let imageData = items.compactMap(imageData(from:)).first {
            let cap = Int(settings.maxImageMB * 1_048_576)
            guard imageData.count <= cap else {
                debug("SKIP image \(imageData.count)b over cap \(cap)b — raise it in Settings → Privacy")
                NSLog("ClipStack: dropped a \(imageData.count / 1_048_576) MB image, over the \(Int(settings.maxImageMB)) MB limit")
                return
            }
            kind = .image
            blob = imageData
            if let rep = NSBitmapImageRep(data: imageData) {
                text = "Size: \(rep.pixelsWide)x\(rep.pixelsHigh)"
            } else {
                text = "Image"
            }
        } else if let rtf = item.data(forType: .rtf),
                  let plain = item.string(forType: .string), !plain.isEmpty {
            kind = .rtf
            blob = rtf
            text = plain
        } else if let plain = item.string(forType: .string) {
            guard !plain.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return }
            kind = .text
            text = plain
        } else {
            debug("SKIP no usable type among \(item.types.map(\.rawValue))")
            return
        }

        let digestSource = blob ?? Data(text.utf8)
        let digest = SHA256.hash(data: digestSource)
            .map { String(format: "%02x", $0) }
            .joined()

        Store.shared.insert(kind: kind, text: text, appName: appName,
                            appBundleID: bundleID, blob: blob, digest: digest)
        Store.shared.prune(to: settings.maxHistory)
        debug("CAPTURED \(kind.rawValue) from \(appName ?? "?") — \(text.prefix(40))")
        onNewClip?()
    }

    /// Normalises whatever image flavour is on the pasteboard into PNG.
    private func imageData(from item: NSPasteboardItem) -> Data? {
        if let png = item.data(forType: .png), !png.isEmpty { return png }
        let convertible: [NSPasteboard.PasteboardType] = [
            .tiff,
            NSPasteboard.PasteboardType("public.jpeg"),
            NSPasteboard.PasteboardType("com.compuserve.gif"),
            NSPasteboard.PasteboardType("public.heic"),
        ]
        for type in convertible {
            guard let data = item.data(forType: type), !data.isEmpty,
                  let rep = NSBitmapImageRep(data: data),
                  let png = rep.representation(using: .png, properties: [:])
            else { continue }
            return png
        }
        return nil
    }

    private var debugEnabled: Bool { DebugLog.isEnabled }

    private func debug(_ message: @autoclosure () -> String) {
        DebugLog.write(message())
    }
}
